[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://images.pexels.com https://cdn.gamepathai.com https://releases.gamepathai.com;
      font-src 'self';
      connect-src 'self' 
        https://*.supabase.co 
        wss://*.supabase.co 
        https://releases.gamepathai.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      media-src 'self';
      worker-src 'self' blob:;
      manifest-src 'self';
      upgrade-insecure-requests;
      block-all-mixed-content
    """

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "no-store, no-cache, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"