[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  # Ignore os erros em dependências nativas não essenciais para o site web
  ignore = "grep -s -q 'registry-js\|unix-dgram\|electron' <<< \"$COMMIT_REF\""

[build.environment]
  NODE_VERSION = "18.16.0"  # Mudando para uma versão LTS mais estável
  # Desabilita a instalação de dependências nativas problemáticas durante o build do Netlify
  NPM_FLAGS = "--no-optional --no-audit --no-fund --ignore-scripts"
  ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
  SHARP_SKIP_DOWNLOAD = "true"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://images.pexels.com https://cdn.gamepathai.com https://releases.gamepathai.com;
      font-src 'self';
      connect-src 'self' https://iafamwvctehdltqmnhyx.supabase.co https://*.supabase.co wss://*.supabase.co https://*.supabase.io wss://*.supabase.io https://releases.gamepathai.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      block-all-mixed-content;
      upgrade-insecure-requests;
      media-src 'self';
      worker-src 'self' blob:;
      manifest-src 'self'
    """

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "no-store, no-cache, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

# Novas configurações para pular módulos problemáticos
[build.processing]
  skip_processing = true

# Configuração específica para evitar erros em módulos nativos
[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false